// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Conor Mc Govern",
            "email": "wheresmylift(at)mcgov(dot)ie"
        },
        "license": {
            "name": "BSD-3-Clause",
            "url": "https://github.com/mcgovman/wheresmylift/blob/main/LICENSE.md"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "tags": [
                    "Root"
                ],
                "summary": "Redirect to swagger docs",
                "responses": {
                    "307": {
                        "description": "Temporary Redirect",
                        "headers": {
                            "Location": {
                                "type": "string",
                                "description": "docs/index.html"
                            }
                        }
                    }
                }
            }
        },
        "/v0/healthcheck": {
            "get": {
                "tags": [
                    "V0"
                ],
                "summary": "Get health of API",
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "WheresMyLift",
	Description:      "Realtime API of the Irish public transit network",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
