#!/bin/sh
#
# Run the following command in the root of your project to install this pre-push hook:
# cp git-hooks/pre-push .git/hooks/pre-push; chmod 700 .git/hooks/pre-push
# @author : Mak Sophea (Extended By Conor Mc Govern)
# @version : 1.0
#

# get the path to this script file
DIR=$(dirname "$0")
COVERAGE_THRESHOLD=97.5

cd api

## Run coverage report
make coverage
TOTAL_COVERAGE=$(make coverage-total)
if [[ $(echo "$TOTAL_COVERAGE $COVERAGE_THRESHOLD" | awk '{print ($1 > $2)}') ]]; then
    echo "Code coverage adequate"
else
    echo "Code coverage is below threshold. Please add more unit tests."
    exit 1
fi

## Run linter
make lint
if [[ $? != 0 ]]; then
    echo -e "\e[31m> linter did not successfully pass\e[0m"
    echo -e "> address linting failures and attempt to push again"
    exit 1
fi

