#!/bin/sh
#
# Run the following command in the root of your project to install this pre-push hook:
# cp git-hooks/pre-push .git/hooks/pre-push; chmod 700 .git/hooks/pre-push
# @author : Mak Sophea (Extended By Conor Mc Govern)
# @version : 1.0

cd packages/api

## Run coverage report
make coverage

## Run linter
make lint
if [[ $? != 0 ]]; then
    echo -e "\e[31m> linter did not successfully pass\e[0m"
    echo -e "> address linting failures and attempt to push again"
    exit 1
fi

cd packages/aggregator

## Run coverage report
make coverage

## Run linter
make lint
if [[ $? != 0 ]]; then
    echo -e "\e[31m> linter did not successfully pass\e[0m"
    echo -e "> address linting failures and attempt to push again"
    exit 1
fi
