---
- hosts: "{{ env }}"
  tasks:
    - name: (Re)create maintenance page container
      community.docker.docker_container:
        name: WML-WEB-UI-maintenance-page
        state: present
        recreate: true
        image: nginx:mainline
        restart_policy: unless-stopped
        labels:
          traefik.enable: "true"
          traefik.http.routers.WML-WEB-UI-maintenance-page.priority: "1"
          traefik.http.services.WML-WEB-UI-maintenance-page.loadbalancer.server.port: "80"
          traefik.http.routers.WML-WEB-UI-maintenance-page.rule: "Host(`{{ endpoint }}`)"
          traefik.http.routers.WML-WEB-UI-maintenance-page.entrypoints: "websecure"
          traefik.http.routers.WML-WEB-UI-maintenance-page.tls: "true"
          traefik.http.routers.WML-WEB-UI-maintenance-page.tls.certresolver: "myresolver"
        networks:
          - name: transit-public
        healthcheck:
          test: ["CMD", "curl", "-I", "-s", "http://localhost", "|", "grep", "'503 Service Temporarily Unavailable'", "&&", "exit", "0"]
          timeout: 1s
          retries: 3
          interval: 5s
    - name: Copy nginx.conf to container
      community.docker.docker_container_copy_into:
        container: WML-WEB-UI-maintenance-page
        content: |
          events {}
          http {
              server {
                  error_page 503 /maintenance.html;

                  location / {
                      return 503;
                  }

                  location = /maintenance.html {
                      root /var;
                      default_type text/html;
                  }
              }
          }
        container_path: /etc/nginx/nginx.conf
        owner_id: 0
        group_id: 0
        mode: "0644"
    - name: Copy maintenance.html to container
      community.docker.docker_container_copy_into:
        container: WML-WEB-UI-maintenance-page
        content: |
          <!doctype html>
          <title>WheresMyLift Maintenance</title>
          <style>
            body { text-align: center; padding: 150px; }
            h1 { font-size: 50px; }
            body { font: 20px Helvetica, sans-serif; color: #333; }
            article { display: block; text-align: left; width: 650px; margin: 0 auto; }
            a { color: #dc8100; text-decoration: none; }
            a:hover { color: #333; text-decoration: none; }
          </style>
          <article>
            <h1>We&rsquo;ll be back soon!</h1>
            <div>
              <p>Sorry for the inconvenience but we&rsquo;re performing some maintenance at the moment. If you need to you can always <a href="mailto:conor+wheresmylift@mcgov.ie">contact us</a>, otherwise we&rsquo;ll be back online shortly!</p>
              <P>Please check our <a href="https://status.wheresmylift.ie">status page</a> to see if we have any ongoing issues.
              <p>&mdash; WheresMyLift Team</p>
            </div>
          </article>
        container_path: /var/maintenance.html
        owner_id: 0
        group_id: 0
        mode: "0644"
    - name: (Re)start maintenance page container
      community.docker.docker_container:
        name: WML-WEB-UI-maintenance-page
        state: healthy