name: Update branch services

on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  changes:
    uses: ./.github/workflows/reusable_changes.yml
  branch:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.branch.outputs.branch }}
    steps:
      - name: Git branch name
        id: branch_name
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/} | sed -r 's/\//-/g')"

  call-setup-api-workspace:
    needs: changes
    if: ${{ needs.changes.outputs.api == 'true' }}
    uses: ./.github/workflows/reusable_setup_workspace.yml
  api-unit-tests:
    needs: call-setup-api-workspace
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Run coverage & print coverage total
        run: |
          pwd
          ls -lah
          make -C api coverage
  api-swagger:
    needs: call-setup-api-workspace
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Verify swagger has been updated
        run: make -C api verify-swagger
  call-build-publish-api:
    needs: [api-unit-tests, api-swagger, branch]
    uses: ./.github/workflows/reusable_build_publish.yml
    with:
      image_names: |
        piongain/wheresmylift-api:${{ needs.branch.outputs.branch }}
      dir: api
    secrets: inherit
  api-deploy:
    needs: [call-build-publish-api, branch]
    uses: ./.github/workflows/reusable_api_deploy.yml
    with:
      image_name: piongain/wheresmylift-api:${{ needs.branch.outputs.branch }}
      endpoint: ${{ needs.branch.outputs.branch }}.dev.api.wheresmylift.ie
    secrets: inherit
  api-venom:
    needs: [api-deploy, branch]
    runs-on: ubuntu-latest
    env:
      ENDPOINT: https://${{ needs.branch.outputs.branch }}.dev.api.wheresmylift.ie
    steps:
      - name: Run venom tests
        run: make -C api venom
