name: Update unstable services

on:
  push:
    branches:
      - 'main'

jobs:
  setup-api-workspace:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Fetch all commits
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23.4'
      - name: Install dependencies
        run: |
          cd api
          go get . || true
          go install github.com/swaggo/swag/cmd/swag@v1.16.4
          curl https://github.com/ovh/venom/releases/download/v1.2.0/venom.linux-amd64 -L -o /usr/local/bin/venom
          chmod +x /usr/local/bin/venom
  call-build-publish-api:
    needs: [call-setup-api-workspace]
    uses: ./.github/workflows/reusable_build_publish.yml
    with:
      image_names: |
        piongain/wheresmylift-api:unstable
      dir: api
    secrets: inherit
  api-deploy:
    needs: [call-build-publish-api]
    uses: ./.github/workflows/reusable_api_deploy.yml
    with:
      image_name: piongain/wheresmylift-api:unstable
      endpoint: dev.api.wheresmylift.ie
    secrets: inherit
  api-venom:
    needs: [api-deploy]
    runs-on: ubuntu-latest
    env:
      ENDPOINT: https://dev.api.wheresmylift.ie
    steps:
      - name: Run venom tests
        run: make -C api venom
