name: Update unstable services

on:
  push:
    branches:
      - 'main'

jobs:
  call-build-publish-api:
    uses: ./.github/workflows/actions/build_publish.yml
    with:
      image_names: |
        piongain/wheresmylift-api:unstable
      dir: api
    secrets: inherit
  api-deploy:
    needs: [call-build-publish-api]
    uses: ./.github/workflows/actions/api_deploy.yml
    with:
      image_name: piongain/wheresmylift-api:unstable
      endpoint: dev.api.wheresmylift.ie
    secrets: inherit
  api-venom:
    needs: [api-deploy]
    runs-on: ubuntu-latest
    env:
      ENDPOINT: https://dev.api.wheresmylift.ie
    steps:
      - uses: ./.github/workflows/actions/setup_workspace.yml
      - name: Run venom tests
        run: make -C api venom
