name: Setup Workspace

on:
  workflow_call:

jobs:
  setup-workspace:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Fetch all commits
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23.4'
      - name: Install dependencies
        run: |
          go get . || true
          go install github.com/swaggo/swag/cmd/swag@v1.16.4
          curl https://github.com/ovh/venom/releases/download/v1.2.0/venom.linux-amd64 -L -o /usr/local/bin/venom
          chmod +x /usr/local/bin/venom
